### ISSUE TITLE
Running without X11 or Wayland

### ISSUE THREAD

**Issue by srekkas** [complexlogic/flex-launcher#47] opened 2023-11-06 06:54 UTC
Hello, 

I am looking for solution for launching Kodi, Supertuxkarts and some other apps who do not require another graphics layer.
Can flex-launcher run without like Kodi with GBM ?

**Comment by complexlogic** [comment] 2024-10-26 16:39
This is a duplicate of #19. I recommend you read the discussion in that issue.

The short summary is that it is technically possible, however, it requires very hackish workarounds. Overall, my belief is that GBM is not worthwhile and Linux users should use X11 with a lightweight window manager. See the [Linux setup guide](https://complexlogic.github.io/flex-launcher/setup_linux#kiosk-mode-setup) for my recommended setup for Linux users.

**Closed by complexlogic** 2024-10-26 16:39 UTC
