### ISSUE TITLE
Request: Option to Support Rows and Columns within a Menu

### ISSUE THREAD

**Issue by StarPlayrX** [complexlogic/flex-launcher#44] opened 2023-10-25 04:25 UTC
Just started using Flex-Launcher after finding so many input-key mappers what would work with Gnome's Desktop but then would over ride and interfere with the games that I am launching. 

For my use case, I would like to show a grid on a each menu where the user can navigate with the game controller or keyboard and select the game or submenu to choose from. This way, They would not have scroll horizontally if the wanted the columns and rows instead.

Thank you for your time and consideration and where I can send a donation. Thanks!

**Comment by complexlogic** [comment] 2024-10-26 16:44
I am not accepting donations for this project, but thank you very much for the offer! This issue is a duplicate of #25.

**Closed by complexlogic** 2024-10-26 16:44 UTC
