### ISSUE TITLE
Could we get support for PWAs?

### ISSUE THREAD

**Issue by PeterDragon50** [complexlogic/flex-launcher#63] opened 2024-11-09 05:40 UTC
I tried to launch a PWA with this app and, while it launches it, the app also keeps the PWA in the background.

**Comment by complexlogic** [comment] 2024-11-09 15:02
I'm guessing this is a duplicate of #49.

I recently pushed a fix for it, but the fix hasn't been incorporated into a new release, yet. Could you try the development build [here](https://github.com/complexlogic/flex-launcher/actions/runs/11533300996/artifacts/2107803809) and let me know if it fixes your issue?

**Comment by PeterDragon50** [comment] 2024-11-09 15:26
This link is 404'd.

**Comment by complexlogic** [comment] 2024-11-09 15:35
You have to access it through a signed-in GitHub account. Clicking it from an email won't work.

**Comment by PeterDragon50** [comment] 2024-11-09 16:36
Gotcha. Thanks for the quick replies. I will try this now.

**Comment by PeterDragon50** [comment] 2024-11-09 16:43
I just tried it. It still stays in the foreground and pushes the PWA into the background.

**Comment by complexlogic** [comment] 2024-11-24 18:44
This is fixed by [v2.2](https://github.com/complexlogic/flex-launcher/releases/tag/v2.2).

**Closed by complexlogic** 2024-11-24 18:44 UTC
